### ISSUE TITLE
Easy way to spoof the bootloop count

### ISSUE THREAD

**Issue by grasscutting** [c22dev/willBootloop#1]
by sending a post request to this url "https://bootloopdb.c22code.repl.co/sumbit?" and putting a funny request body you can spoof the bootloop count 🍾 it seems like this is already being abused.

**Comment by c22dev** [comment]
Hi, thanks for your report. I will change server API function soon.

Backup got restored by server because it detected unusual number.

**Comment by c22dev** [comment]
Can you send me your request body ?

**Comment by grasscutting** [comment]
remove the code for the api so it won't be abused 🔥

**Comment by c22dev** [comment]
Again, could you send me the request body you are talking about ? I can't remove the code for the api as it's literally how submit work. Improved IP Blacklisting btw, can you try again ?

**Comment by grasscutting** [comment]
sure, one second

**Comment by grasscutting** [comment]
you blacklisted my ip 😭

**Comment by grasscutting** [comment]
it seems like the method you have for blacklisting is good

the request body is

{
  "packageID": "1",
}

in this case "1" would be misaka? (i think)

**Comment by grasscutting** [comment]
here's a shortcut i made that in theory would've worked. https://www.icloud.com/shortcuts/9bfe85de2c7743f1a7e9db7b7222a979

**Comment by c22dev** [comment]
This basically just add one bootloop value, as you would do by using the website. New IP Blacklister only allow one request per week per ip. I'll close this issue, feel free to open it back if you find anything else.

**Comment by grasscutting** [comment]
well this aged well 😭

**Comment by c22dev** [comment]
true
